### ISSUE TITLE
infitech2 upgrade problem

### ISSUE THREAD

**Issue by adamsonich** [Blood-Asp/gregtech5exp#3]
Me and my friends played some version of infitech 2 modpack with gregtech v26 and without galacticraft. I make update upto v3.1.21 of infitech2 with gregtech v32 and with GC. Input hatch as part of EBF stoped drain oxygen. if I delete GC then input hatch starts drain oxygen.
as i can see, problem is oxygen oredict beetwin GC and GT.

How resolve problem?

I can upload 2,3MB world-save with same problem.
I will repost it in infitech2 issue theard.

**Comment by Blood-Asp** [comment]
That is a known issue but possible to fix.

open the level.dat of your world save with NBT explorer, go to Forge/DefaultFluidList and delete the broken fluids.
