### ISSUE TITLE
Advanced Miner II causes extreme TPS lag

### ISSUE THREAD

**Issue by PaulMadsen** [Blood-Asp/gregtech5exp#4]
This occurs when its input hatch has between 1 and 99 drilling fluid in it, inclusive.  Once the chunk it resides in is unloaded the dimension it is located in experiences extreme TPS lag.  /cofh tps shows .5 TPS. 
Also, when the loaded the drill will continue to operate despite not having enough drilling fluid to complete an operation.

**Comment by JasonMcRay** [comment]
This repo is no longer maintained. Please report GT problems in the classic GregTech repo: https://github.com/Blood-Asp/GT5-Unofficial/issues

**Comment by Blood-Asp** [comment]
i should close the whole repo...
